// <auto-generated />
using KoreatechGraduateManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KoreatechGraduateManagement.Migrations.MvcGraduateCredit
{
    [DbContext(typeof(MvcGraduateCreditContext))]
    partial class MvcGraduateCreditContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("KoreatechGraduateManagement.Models.GraduateCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CoreClassNecessaryCredit")
                        .HasColumnType("int");

                    b.Property<int>("CoreClassNormalCredit")
                        .HasColumnType("int");

                    b.Property<int>("ElectivesNecessaryCredit")
                        .HasColumnType("int");

                    b.Property<int>("ElectivesNormalCredit")
                        .HasColumnType("int");

                    b.Property<string>("EntranceYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FreeCredit")
                        .HasColumnType("int");

                    b.Property<int>("HRDClassNecessaryCredit")
                        .HasColumnType("int");

                    b.Property<int>("HRDNormalCredit")
                        .HasColumnType("int");

                    b.Property<int>("MSCNecessaryCredit")
                        .HasColumnType("int");

                    b.Property<int>("MSCNormalCredit")
                        .HasColumnType("int");

                    b.Property<int>("TotalGraduateCredit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GraduateCredit");
                });
#pragma warning restore 612, 618
        }
    }
}
